# Site settings
title: Capstone Project - Overuse Injury Prevention Program
email: judykim.ot@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl:  # the subpath of your site, e.g. /blog/
url: "https://jkimotd.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
